### ISSUE TITLE
Tinder started rejecting the bot

### ISSUE THREAD

**Issue by Tom1380** [scoliann/TinderFaceScraper#13]
So I was trying the bot for the first time and everything was going well, until it crashed. I didn't think much of it,  but when I tried again it started giving me errors everytime `Traceback (most recent call last):
  File "./tinderGetPhotos.py", line 93, in <module>
    x_auth_token = tinderAPI_get_xAuthToken(facebook_token, facebook_id)
  File "./tinderGetPhotos.py", line 34, in tinderAPI_get_xAuthToken
    x_auth_token = r.json()['token']
KeyError: 'token'
`
So I added a print statement of r.json(), and this is the output `{'code': 401, 'error': 'Access Denied'}`. I know what this means, but why isn't tinder letting me login anymore? I can still login and use the app from my phone normally.

**Comment by Tom1380** [comment]
Never mind. Apparently my token changed. Maybe it stopped working at midnight? I don't know.
